language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  bucket: kuropen.org
  access_key_id: AKIAIVYV7PWVZZJIK2VA
  local_dir: build
  on:
    branch: master
  secret_access_key:
    secure: gD3rj/7hWFV05wqALcwTBNHqoMpLNfeo2HlYCpUbF2JwXkQkTPu7sIL4x5AocW+PVRcAX0+gz7F6S/+M6VAP2fSxu4yfJGegPuXtF4FPJupAfR7QcKp8J8m43bEo4UYM8N6e6xwI72wS5MsDIafVd0oYm5nWOmM6bjkcP/EJOs6X18sjklKJRLI2iEped/uLgov7dP+tZsihfpfmbxuj5avGuX+X8bEdEO9XkWN4HG7ildn78JOpBsXxnanLK9v4Cv4YHBKA9eZeVBaJII9y9BUUV51d2cN+3zyL4Cg1XT30WlAn4fiy3QGPK2YK9LFZDaC5R+ZvdnHN19T44r/wO/gNZi6eJa3l+Dl2taYFO2ZFEJ+JGKSf5IEjGnxpn5kSMbKapYGu/RwOUZlOBlarC+fna05r0hCtwQgm3VF4Jk415obE/7ipFOdtrUS+ThbbxCUVyeVXYKk5pgbBCyDHU+9oxLvOKZnO2kvUvwHoXlD5prAvRyALEOxX1gFqh6rf5Tqdd1sG4quxsCiV7w+KiwiW9VQfgdT5um38SvZEDxJ7Sy78HDEJEAsCtRIO4zgNXy+eV1xLFJVu8I+mNj1UkkMxy9xO+l07dSMKRp1RQl1XvFOmabsmvz/FgnPa834b5HX7j51B03MTI/nf/CAYditPnuOFzqQfrfAxCqLn4Qo=
